### ISSUE TITLE
load_dotenv() is called no matter what

### ISSUE THREAD

**Issue by entropi** [peopledatalabs/peopledatalabs-python#150]
**Describe the bug**
[It appears](https://github.com/peopledatalabs/peopledatalabs-python/blob/8bc0917835588046417c1c602d16ce15db36c29e/src/peopledatalabs/settings.py#L35) that load_dotenv() is called by this library no matter what, which can have impact on the entire operating environment if running in a situation where the user does not expect this behavior. 

**To Reproduce**
Use/load the module, without calling load_env() in the calling program, and see that any environment variables you set in .env are now visible in os.environ. 

**Expected behavior**
I would not ever expect a third party module to automatically call load_dotenv() for me, because of the impact across the entire operating environment for the running process.  Instead, I'd expect the library to simply document what environment variables I can set for configuration, and if I choose to use .env to set them I can load_dotenv() myself before using the module.

**Additional context**
Causes issues outside of the module itself if load_dotenv() calling is not expected.

**Comment by entropi** [comment]
Ideally `python-dotenv` would be a dev-dependency at best for the library.

**Comment by vvillait88** [comment]
@entropi Thanks for opening the issue.  We will look into this and provide an update next week.

**Comment by vvillait88** [comment]
@entropi this is addressed in version 4.0.0 as we considered it a positive but breaking change

**Comment by entropi** [comment]
Thank you!
