### ISSUE TITLE
Support for sandbox API endpoints

### ISSUE THREAD

**Issue by Layvier** [peopledatalabs/peopledatalabs-python#16]
Hi,

we're starting to integrate PDL into our backend. For our local and sandbox environments, we would like to use the sandbox API endpoints (https://docs.peopledatalabs.com/docs/sandbox-apis). However it seems that this client doesn't support it out of the box, the only way seems to set a BASE_PATH environment variable (from this [line](https://github.com/peopledatalabs/peopledatalabs-python/blob/38e28e94a2730389b83c4edf4b23ea9f3c2576f3/src/peopledatalabs/settings.py#L37)). The issue with this approach is that the naming of this variable is confusing, ideally it would be something like PDL_BASE_PATH.

Actually I'd suggest prefixing by **PDL_** all environment variables that would override the settings to avoid conflicts with existing env vars.

Let me know what you think,

Cheers, Olivier

**Comment by Layvier** [comment]
Just noticed https://github.com/peopledatalabs/peopledatalabs-python/pull/15 will add sandbox support, my bad will close the issue. Thanks!

**Comment by martimlobao** [comment]
@Layvier Yup, we just release the sandbox API not even a month ago, we should be releasing an updated python package very soon :)

**Comment by Layvier** [comment]
That's awesome, thanks a lot:)

**Comment by vvillait88** [comment]
@Layvier We just merged PR https://github.com/peopledatalabs/peopledatalabs-python/pull/15
