### ISSUE TITLE
`InvalidEndpontError`: Invalid method __post_init_post_parse (Pydantic validation error) when calling multiple endpoints with SDK

### ISSUE THREAD

**Issue by camin-mccluskey** [peopledatalabs/peopledatalabs-python#17]
**Describe the bug**
`InvalidEndpontError` for endpoints:

- Elasticsearch search
- Bulk enrichment
- Job search

![Screenshot 2022-09-05 at 18 01 35](https://user-images.githubusercontent.com/18604525/188492740-8e219d7c-5e73-4066-bd5a-f6b188b485e4.png)

**To Reproduce**
Minimal reproduction

![Screenshot 2022-09-05 at 18 01 52](https://user-images.githubusercontent.com/18604525/188492770-625a4b26-90a5-43a3-bb96-870532aa9a63.png)

**Expected behavior**
Endpoints return results

**Screenshots**
 - peopledatalabs Library Version 1.1.0
 - Python Version 3.10.0

**Additional context**
Calling these endpoints, with the Python SDK was working correctly a few days ago and I've confirmed the endpoints are working correctly when the same parameters are passed directly to the API via an HTTP client

**Comment by vvillait88** [comment]
@camin-mccluskey I've tried replicating your issue and cannot.  You can find that here (I've removed the API Key but you can see the result printed fine): https://colab.research.google.com/drive/1Y739v9Fav9SKekErBtiVQJkuFswE5D6U?usp=sharing

**Comment by camin-mccluskey** [comment]
@vvillait88 Thanks for the prompt response. It seems both you and some members of my team can run the above code so I imagine it's a possible version issue on my machine. I've tried 3.10.0 and 3.9.6 (I'm not sure what version collab is utilising, I believe it's 3.6.9 by default). I will close this issue as it seems there is nothing to be done on the SDK side.

**Comment by vvillait88** [comment]
@camin-mccluskey we were able to track it down to the pydantic version.  I just pushed an update that should fix this for you.
