### ISSUE TITLE
Replace version pegs with minimum required versions

### ISSUE THREAD

**Issue by ngould** [peopledatalabs/peopledatalabs-python#24]
This library currently pegs all dependencies to specific versions (i.e. using `==` in `requirements.txt`), instead of specifying minimum required versions (i.e. using `>=`). This practice makes it difficult to use this library in the context of larger projects, which are likely to have conflicting dependencies.

For example, I just tried installing this in a project that uses [Prefect](https://github.com/PrefectHQ/prefect), and got this error:

![image](https://user-images.githubusercontent.com/3130631/207419000-c5f52e20-8e2f-4dd4-9bf5-556c5b138ad9.png)

These problems can be avoided if the People Data Labs library specifies minimum requirements, or version ranges where needed.

**Comment by ded-ditat** [comment]
I have this same exact error. Pydantic version is incompatible with the minimum required pydantic version with prefect. 

Same exact error please specify minimum requirements or version ranges so we can use this sdk with our projects. 

We're an enterprise peopledatalabs customer as well.

**Comment by martimlobao** [comment]
@ngould @ded-ditat Just opened a PR which hopefully addresses the issue. One note is that the constraints shouldn't be getting set by `requirements.txt` but rather by `pyproject.toml`. If you `pip install` this package, you should see `pydantic<1.10,>=1.8`:

```sh
$ pip install peopledatalabs       
Collecting peopledatalabs
  Downloading peopledatalabs-1.1.6-py3-none-any.whl (17 kB)
Requirement already satisfied: requests<3,>=2 in ... (from peopledatalabs) (2.28.2)
Collecting python-dotenv<1,>=0
  Downloading python_dotenv-0.21.1-py3-none-any.whl (19 kB)
Requirement already satisfied: pydantic<1.10,>=1.8 in ... (from peopledatalabs) (1.9.2)
...
```
