### ISSUE TITLE
Trying to upgrade to pydantic > 2.0 is blocked by peopledatalabs

### ISSUE THREAD

**Issue by avilaton** [peopledatalabs/peopledatalabs-python#93]
**Describe the bug**
We are trying to upgrade a project dependency to pydantic > 2.0 and are blocked by not having a version of this project that supports it.

**To Reproduce**
poetry add pydantic==^2.0

**Expected behavior**
There could be a version of this package that was compatible with newer versions of pydantic

**Screenshots**
 - peopledatalabs Library Version: 2.0.1
 - Python Version 3.10

**Comment by vvillait88** [comment]
@avilaton version 3.0.0 will fix this issue
